import {
    TuiAlertModule,
    TuiButtonModule,
    TuiCalendarModule,
    TuiCalendarSheetPipeModule,
    TuiDataListModule,
    TuiDialogModule,
    TuiDropdownModule,
    TuiErrorModule,
    TuiExpandModule,
    TuiFlagPipeModule,
    TuiFormatDatePipeModule,
    TuiFormatNumberPipeModule,
    TuiFormatPhonePipeModule,
    TuiGroupModule,
    TuiHintModule,
    TuiHintsHostModule,
    TuiHostedDropdownModule,
    TuiLabelModule,
    TuiLinkModule,
    TuiLoaderModule,
    TuiMaskAccessorModule,
    TuiModeModule,
    TuiMonthPipeModule,
    TuiNotificationModule,
    TuiNumberFormatModule,
    TuiPrimitiveCalendarModule,
    TuiPrimitiveCheckboxModule,
    TuiPrimitiveSpinButtonModule,
    TuiPrimitiveTextfieldModule,
    TuiPrimitiveYearMonthPaginationModule,
    TuiPrimitiveYearPickerModule,
    TuiRootModule,
    TuiScrollIntoViewModule,
    TuiScrollbarModule,
    TuiSvgDefsHostModule,
    TuiSvgModule,
    TuiTextfieldControllerModule,
    TuiThemeNightModule,
    TuiTooltipModule,
    TuiWrapperModule,
} from '@taiga-ui/core';
import { TuiValueAccessorModule } from '@taiga-ui/kit';
// import { TuiLineDaysChartModule } from '@taiga-ui/addon-charts';

// todo: remove unused modules

export const TAIGA_MODULES = [
    TuiAlertModule,
    TuiButtonModule,
    TuiCalendarModule,
    TuiCalendarSheetPipeModule,
    TuiDataListModule,
    TuiDialogModule,
    TuiDropdownModule,
    TuiErrorModule,
    TuiExpandModule,
    TuiFlagPipeModule,
    TuiFormatDatePipeModule,
    TuiFormatNumberPipeModule,
    TuiFormatPhonePipeModule,
    TuiGroupModule,
    TuiHintModule,
    TuiHintsHostModule,
    TuiHostedDropdownModule,
    TuiLabelModule,
    TuiLinkModule,
    TuiLoaderModule,
    TuiMaskAccessorModule,
    TuiModeModule,
    TuiMonthPipeModule,
    TuiNotificationModule,
    TuiNumberFormatModule,
    TuiPrimitiveCalendarModule,
    TuiPrimitiveCheckboxModule,
    TuiPrimitiveSpinButtonModule,
    TuiPrimitiveTextfieldModule,
    TuiPrimitiveYearMonthPaginationModule,
    TuiPrimitiveYearPickerModule,
    TuiRootModule,
    TuiScrollIntoViewModule,
    TuiScrollbarModule,
    TuiSvgDefsHostModule,
    TuiSvgModule,
    TuiTextfieldControllerModule,
    TuiThemeNightModule,
    TuiTooltipModule,
    TuiWrapperModule,
    // addon-charts
    // TuiLineDaysChartModule,
];
